source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'TriHealth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TriHealth
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
